wesleybowman/UTide

MANIFEST.in
Added a `MANIFEST.in` so user can create a source distribution with `python setup.py sdist`.
=> Added `MANIFEST.in`.

utide/__init__.py, utide/comparison.py, utide/master.py, utide/masterRec.py, utide/robustfit.py, utide/simple_utide_test.py, utide/ut_E.py, utide/ut_FUV.py, utide/ut_astron.py, utide/ut_cnstitsel.py, utide/ut_confidence.py, utide/ut_diagn.py, utide/ut_fbndavg.py, utide/ut_linci.py, utide/ut_lmbscga.py, utide/ut_pdgm.py, utide/ut_rcninit.py, utide/ut_reconstr1.py, utide/ut_slvinit.py, utide/ut_solv.py, utide/ut_solv1.py
This PR seems massive, but the code changes are actually almost zero.  I just applied [pep8](https://www.python.org/dev/peps/pep-0008/) rules and made some [pyflakes](https://launchpad.net/pyflakes) adjustments to lower the bar for future contributors.
The next step is to build some tests...
=> PEP8 and PyFlakes fixes.

utide/__init__.py, utide/comparison.py, utide/master.py, utide/masterRec.py, utide/robustfit.py, utide/simple_utide_test.py, utide/ut_E.py, utide/ut_FUV.py, utide/ut_astron.py, utide/ut_cnstitsel.py, utide/ut_confidence.py, utide/ut_cs2cep.py, utide/ut_diagn.py, utide/ut_fbndavg.py, utide/ut_linci.py, utide/ut_lmbscga.py, utide/ut_pdgm.py, utide/ut_rcninit.py, utide/ut_reconstr.py, utide/ut_reconstr1.py, utide/ut_slvinit.py, utide/ut_solv.py, utide/ut_solv1.py
That was easy (thanks to #9).  This PR closes #11.
Now moving on to the tests...
=> Code base works with py3 and py27.

.gitignore, utide/__init__.py, utide/master.py, utide/simple_utide_test.py, utide/ut_FUV.py, utide/ut_cnstitsel.py, utide/utilities.py
We are also taking some convenience functions from python-gsw
(and originally from pycurrents) in the new utilities module.
At this point, simple_utide_test runs.
=> Read ut_constants.mat when the module is imported.

utide/ellipse_params.py
I made a docstring indentation error in the original.
In addition to fixing that, I replaced the matlab docstring with one matching the python arguments, and made the code a little nicer.  I came across an oddity which I suspect should be fixed both here and in the matlab: the semi-minor axis output can be negative.  For consistency with the original I left this in place for now.
=> ellipse_params: fix docstring indentation; edit code and docstring

utide/__init__.py, utide/_solve.py, utide/confidence.py, utide/constituent_selection.py, utide/simple_utide_test.py
This is a mixture of cleanups and added comments.
=> Miscellaneous simplifications and readability tweaks.

.travis.yml, requirements.txt, setup.cfg, setup.py
@wesleybowman do not merge this yet!
Before merging I would like to get [travis-ci](https://travis-ci.org/) working for the PRs.
- Do you have a travis-ci account?  (You can login using you GitHub credentials.)
- Can you enable travis for this repository?  (There is a "turn on" switch for that.)
Let me know if you need any help setting this up.
=> Basic testing framework

utide/harmonics.py
I am not sure if the code is doing the right thing there, but I found this bug while experimenting with the available options.
=> Minor bug fix.

doc/internals/index.rst, doc/internals/robustfit.rst, utide/_solve.py, utide/robustfit.py, utide/tests/test_solve.py
As with everything here, there is more to be done in testing, argument handling, and documentation; but I think this is good enough now to be worth merging.
=> Add robust MLR capability.

README.md
Most of README.md was obsolete.
=> DOC: major update of README

tests/test_periodogram.py, tests/test_solve.py, utide/_solve.py, utide/confidence.py, utide/utilities.py
A minimal test for this has been added.
=> BUG: fix the handling of NaN or masked values.

utide/harmonics.py
=> Fix bug with latest numpy

README.rst
Goes along with https://github.com/wesleybowman/UTide/issues/45
=> Add new badges to the README

.travis.yml, README.rst
=> remove outdated dev stuff from the README

.travis.yml, requirements-dev.txt, tests/test_HNL.py, tests/test_astron.py, tests/test_harmonics.py, tests/test_normalize.py, tests/test_periodogram.py, tests/test_solve.py, tests/test_uv.py, utide/_solve.py, utide/confidence.py, utide/utilities.py
Ping @efiring
This is not a hard fail but would've helped find the issues with #56.
One alternative that I like is stickler-ci. stickler-ci runs and add comments in the line of the PR.
=> actually run coding standards_tests

.travis.yml, README.rst
Exactly what is says above :smile:
=> remove percentages

.travis.yml
@wesleybowman this is just to ensure we are OK with #73. All tests are passing so we are either OK or we need better test coverage :smile:
=> test latest python with old and new numpy

utide/periodogram.py
=> Modify periodogram to work around scipy v1.7.x bug

.github/workflows/tests.yml, .pre-commit-config.yaml, utide/constituent_selection.py
Investigate the failures in #99
=> Update freqs take2

pyproject.toml
Should fix https://github.com/wesleybowman/UTide/pull/115#issuecomment-1599274494
=> add missing dynamic entry

.github/workflows/tests.yml
=> update for NEP29

.github/workflows/pre-commit.yml
Looks like the dependabot is stuck in #121
=> alternative to #121

.github/workflows/tests.yml
This is not exactly SPEC 0 b/c that one is too restrict but it bumps the min numpy, add py313, and add numpy 2 to the test matrix.
=> Add py313 and np2 tests

.github/dependabot.yml, .github/workflows/deploy-docs.yml, .github/workflows/pre-commit.yml, .github/workflows/pypi.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, notebooks/utide_real_data_example.ipynb, notebooks/utide_uv_example.ipynb, pyproject.toml, tests/test_astron.py, tests/test_periodogram.py, tests/test_solve.py, tests/test_uv.py, utide/__init__.py, utide/_solve.py, utide/data/make_FUV_data.py, utide/utilities.py
Closes https://github.com/wesleybowman/UTide/issues/137
=> Remove pkg resources
